### ISSUE TITLE
Unable to add WGLMakie.jl due to package versions

### ISSUE THREAD

**Issue by jane2L** [JuliaPlots/WGLMakie.jl#11]
When following the installation guide with this package, I had some unsatisfiable requirements error when trying to run the following in a Julia console:

![image](https://user-images.githubusercontent.com/25347372/65217178-9f3e9700-daf6-11e9-8a84-194ddf8f7229.png)

Is there a way at this stage to use WGLMakie (specifically for display in Jupyter Notebooks)?
That would be great!!

**Comment by SimonDanisch** [comment]
updated the README!
