### ISSUE TITLE
[FR] Export of plot as pluggable javascript

### ISSUE THREAD

**Issue by tlienart** [JuliaPlots/WGLMakie.jl#38]
I'll keep that here as a way to track the issue, hope that's ok. 

My hope is to be able to produce a graph in Julia using WGLMakie and get javascript output that I can serve on a static website. Similar to PlotlyJS. 

Thanks!

**Comment by SimonDanisch** [comment]
This is actually possible by now:
```julia
using JSServe, WGLMakie, AbstractPlotting

function handler(session, request)
    return scatter(1:4, color=1:4)
end

dir = joinpath(@__DIR__, "test")
mkdir(dir)
JSServe.export_standalone(handler, dir)
# Then serve it with e.g. LiveServer
using LiveServer

LiveServer.serve(dir=dir)
```
Note though, as long as we dont move more functionality to JS, this mostly removes all interactivity!

**Comment by tlienart** [comment]
awesome, thanks, I'll add that in the examples with Franklin
