### ISSUE TITLE
Hanging in Jupyter

### ISSUE THREAD

**Issue by cjdoris** [JuliaPlots/WGLMakie.jl#39]
I'm trying to run the simple example in the README in Jupyter:
```julia
using AbstractPlotting, WGLMakie
scatter(rand(10))
```
and it just hangs. It's been sat there heating up my CPU for about 10 minutes now. I don't know where to start figuring out what's going wrong --- I'm not aware of any debuggers that work in Jupyter.

Any suggestions? Thanks!

Christopher

**Comment by urlicht** [comment]
I also have the same issue on Ubuntu 18.04, Julia 1.4

**Comment by SimonDanisch** [comment]
This may happen if you have another session open with JSServe... You need to set the port in this case:

```julia
# In your very first IJulia/Pluto cell:
using JSServe, WGLMakie
Page(listen_port=rand(8000:9000))
```
http://juliaplots.org/WGLMakie.jl/dev/#Pluto/IJulia
