### ISSUE TITLE
Plot points to ip '0.0.0.0'

### ISSUE THREAD

**Issue by Eggiverse** [JuliaPlots/WGLMakie.jl#60]
I am trying to use WGLMakie with Pluto on my PC.

The plot result cannot be shown in the notebook.

The browser (chrome or firefox) suggests that the plot is in http://0.0.0.0:8081/......

However, the browser cannot load anything from ip '0.0.0.0'. 
Forcing the browser to load from '127.0.0.1' solves the problem.

**Comment by SimonDanisch** [comment]
You can change those values, before displaying something:
https://github.com/SimonDanisch/JSServe.jl/blob/47932db39f80c5854bb99755a3397930d63b4d00/src/JSServe.jl#L39

**Comment by Eggiverse** [comment]
Shouldn't WGLMakie do something about it?

I find it quite unfriendly to have something like 
```julia
import JSServe
JSServe.JSSERVE_CONFIGURATION.listen_url[] = "127.0.0.1"
```
when using Makie.

**Comment by SimonDanisch** [comment]
Suure...But time :P 

But, I do want to work on a better Pluto integration in the future

**Comment by Eggiverse** [comment]
It seems the issue has been fixed in [JSServe](https://github.com/SimonDanisch/JSServe.jl/commit/cd8443e9bc8b2b4721a43817b0edb0fa8824b3fa)

For WGLMakie, modify compat for JSServe is the only thing to do now.

**Comment by jtrakk** [comment]
Serving on 0.0.0.0 means opening the plots to external network requests, which might be a security hazard if that's not what users expect.

**Comment by SimonDanisch** [comment]
Yes, that's true... Well, it's changed now!
