### ISSUE TITLE
Default scene resolution too large

### ISSUE THREAD

**Issue by tomyun** [JuliaPlots/WGLMakie.jl#62]
When I rendered a 3D scene on Jupyter Notebook, the scene got rendered too large that it didn't fit in a cell. I couldn't even find a way to pan this scene to the center.

Here is a [meshscatter example](http://juliaplots.org/MakieReferenceImages/gallery/meshscatter_function/index.html).

```
using GeometryBasics
using AbstractPlotting, WGLMakie

large_sphere = Sphere(Point3f0(0), 1f0)
positions = decompose(Point3f0, large_sphere)
colS = [RGBAf0(rand(), rand(), rand(), 1.0) for i = 1:length(positions)]
sizesS = [rand(Point3f0) .* 0.05f0 for i = 1:length(positions)]
scene = meshscatter(positions, color = colS, markersize = sizesS)
```

<img width="1164" alt="Screen Shot 2020-10-16 at 8 49 25 PM" src="https://user-images.githubusercontent.com/906626/96327761-15127c00-0ff1-11eb-8ba4-dc9432f4ea12.png">

Then it turns out `scene.resolution` was set to `(2560, 1440)` which is the size of my display (27-inch iMac).
If I manually set a small resolution (*i.e.* `(500, 500)` in the example below), then it works fine.

<img width="747" alt="Screen Shot 2020-10-16 at 8 47 02 PM" src="https://user-images.githubusercontent.com/906626/96327806-dc26d700-0ff1-11eb-9433-a6645e7ab1a1.png">

It'd be great if we could have a more sensible value for the default resolution.
I tested it with WGLMakie 0.2.9, Julia 1.5.2 and IJulia 1.21.4 on macOS using Chrome 86.

**Comment by SimonDanisch** [comment]
Defaults should be more reasonable now!
