### ISSUE TITLE
No rendering on Safari

### ISSUE THREAD

**Issue by tomyun** [JuliaPlots/WGLMakie.jl#63]
<img width="1168" alt="Screen Shot 2020-10-16 at 9 04 17 PM" src="https://user-images.githubusercontent.com/906626/96327979-31afb380-0ff3-11eb-840b-eb808da6b0f7.png">

Tested with WGLMakie 0.2.9 and IJulia 1.21.4 on Julia 1.5.2. Browser was Safari 14.0 on macOS 10.15.
The same code worked fine (except the resolution issue) on Chrome browser as shown in #62.

**Comment by SimonDanisch** [comment]
Yeah, people should just not use Safari, if Apple isn't willing to implement basic features...
I on the other hand could show a warning, I suppose ^^ Any PRs for that are welcome!

**Comment by ivirshup** [comment]
@tomyun, it works for me in safari through jupyter lab. You might need to opt-in to webgl support by ticking `Develop > Experimental Features > WebGL 2.0`

**Comment by SimonDanisch** [comment]
I think WGLMakie should now also show a warning if WebGL isn't working...

**Comment by mananbordia** [comment]
3d interactive plot doesn't render properly.

This is what I am receiving - 

<img width="431" alt="Screenshot 2021-05-29 at 4 02 06 PM" src="https://user-images.githubusercontent.com/45929094/120067241-14b68500-c098-11eb-8fb7-7a9d10b7b892.png">

Expected Plot [ got this in atom ]

<img width="411" alt="Screenshot 2021-05-29 at 4 07 14 PM" src="https://user-images.githubusercontent.com/45929094/120067250-2861eb80-c098-11eb-81e6-4dfa3f412464.png">
