### ISSUE TITLE
Missing colors (lighting) with mesh

### ISSUE THREAD

**Issue by tomyun** [JuliaPlots/WGLMakie.jl#64]
When I ran [color mesh example](http://juliaplots.org/MakieReferenceImages/gallery/merged_color_mesh/index.html), I couldn't get colors/lighting with a mesh with `color` metadata.

<img width="919" alt="Screen Shot 2020-10-16 at 9 15 57 PM" src="https://user-images.githubusercontent.com/906626/96328166-c9fa6800-0ff4-11eb-90e2-61705612db43.png">

It's not a completely dark black though as I noticed a bit of specular reflection on some directions. The same example worked fine with colors as expected on GLMakie. Also note that examples like [meshscatter](http://juliaplots.org/MakieReferenceImages/gallery/meshscatter_function/index.html) had no problems showing colors on WGLMakie (#62).

Tested with WGLMakie 0.2.9, IJulia 1.21.4 and Julia 1.5.2 on macOS using Chrome 86.

**Comment by SimonDanisch** [comment]
This is working in the newest release:
![image](https://user-images.githubusercontent.com/1010467/119731575-6502cc80-be77-11eb-82b6-26b171a72846.png)
