### ISSUE TITLE
most recent tagged release broke Pluto.jl support

### ISSUE THREAD

**Issue by gszep** [JuliaPlots/WGLMakie.jl#75]
`WGLMakie v0.2.9 ⇒ v0.2.10` broke examples https://github.com/fonsp/Pluto.jl/issues/779 that use to work https://github.com/fonsp/Pluto.jl/issues/155

**Comment by SimonDanisch** [comment]
I think I just figured out what happened... Should have tested this more :D `AbstractPlotting.inline!(true)` should fix it! I defaulted to the exact opposite for what it should be in Pluto :D

**Comment by gszep** [comment]
yep that line does the trick! I'm having so much fun with `WGLMakie.jl` and `Pluto.jl` together! Thank you :smile:
