### ISSUE TITLE
disabling the context menu on right-click

### ISSUE THREAD

**Issue by gszep** [JuliaPlots/WGLMakie.jl#76]
Moved issue from: https://github.com/fonsp/Pluto.jl/issues/789. Apparently you can disable it [using a little bit of Javascript](https://stackoverflow.com/questions/51958065/prevent-context-menu-from-opening-on-a-right-click-over-element/51958093). How do I disable it in Pluto? It is interfering with the plot panning interactions
![Screenshot from 2020-12-19 18-00-32](https://user-images.githubusercontent.com/17977117/102694892-3af01300-4224-11eb-9943-c2b2dbf7cd82.png)

**Comment by SimonDanisch** [comment]
I tried this once and removed it, since it was unreliable and let to other problems.. I think we should just change the shortcut for WGLMakie!

**Comment by koehlerson** [comment]
would love to change it. Do you have a pointer for me where I have to look for the binding?

**Comment by SimonDanisch** [comment]
@jkrumbiegel can we actually customize the camera to use another button?
@koehlerson, I guess we can put the javascript pointed out by @gszep into wglmakie.js, as a stop gap solution ;)

**Comment by jkrumbiegel** [comment]
yeah you can change it but it seems really that disabling the context menu has to be the way to go, why lose one mouse button to this useless thing :)

**Comment by SimonDanisch** [comment]
I just remember it wasn't working very well :D But I guess we should try it nevertheless and see how it goes...
