### ISSUE TITLE
The example is NOT working !

### ISSUE THREAD

**Issue by touchft** [JuliaPlots/WGLMakie.jl#80]
run the example code in REPL
"""
using AbstractPlotting, WGLMakie

scatter(rand(4))
"""

and get in REPL
"""
┌ Warning: Showing scene as text. This happens because `AbstractPlotting.inline!(true)` is set.
│ This needs to be false to show a plot in a window when in the REPL.
└ @ AbstractPlotting ~/.julia/packages/AbstractPlotting/q9DyS/src/display.jl:132
Scene (960px, 540px):
events:
    window_area: GeometryBasics.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set{AbstractPlotting.Mouse.Button}()
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set{AbstractPlotting.Keyboard.Button}()
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis2D{...}
   *Scatter{...}
subscenes:
   *scene(960px, 540px)
"""

Change code with `AbstractPlotting.inline!(false)`

and get in REPL:
"""
Scene (960px, 540px):
events:
    window_area: GeometryBasics.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set{AbstractPlotting.Mouse.Button}()
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set{AbstractPlotting.Keyboard.Button}()
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis2D{...}
   *Scatter{...}
subscenes:
   *scene(960px, 540px)
""" 

**No browser tab is OPENED ! No display!**

**Comment by SimonDanisch** [comment]
How do you run this?
JSServe tries to only enable the browser display, if there isn't any other HTML enabled display.
You should try putting this in the beginning:
```
JSServe.browser_display()
```

**Comment by ecollins** [comment]
@SimonDanisch , the example implies that it will run out-of-the-box, but there's clearly some kind of extra setup required.

I get different output, but the same problem. JSServe.browers_display() just reports `Info: Already in there!`
Running the example in the REPL:

```
using AbstractPlotting, WGLMakie
scatter(rand(4))
```
Yields
```
[ Info: Makie/AbstractPlotting is caching fonts, this may take a while. Needed only on first run!
Scene (600px, 400px):
  18 Plots:
    ├ Combined{AbstractPlotting.poly,Tuple{Array{Array{Point{2,Float32},1},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.annotations,Tuple{Array{Tuple{String,Point{2,Float32}},1}}}
    ├ Combined{AbstractPlotting.text,Tuple{String}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.annotations,Tuple{Array{Tuple{String,Point{2,Float32}},1}}}
    ├ Combined{AbstractPlotting.text,Tuple{String}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    └ Combined{AbstractPlotting.text,Tuple{String}}
  1 Child Scene:
    └ Scene (495px, 302px)
```

If there are additional requirements or dependencies to get get a Makie figure to display, they should probably be spelled out for users who aren't already plugged into the larger ecosystem.

**Comment by SimonDanisch** [comment]
Hm, seems like that's actually broken...

**Comment by SimonDanisch** [comment]
It's actually just the default that is wrong (It doesn't set `AbstractPlotting.inline!(false)` for the repl). Fixed in: https://github.com/JuliaPlots/WGLMakie.jl/pull/94
