### ISSUE TITLE
Failing to create a usable precompiled cache file for WGLMakie

### ISSUE THREAD

**Issue by woolstar** [JuliaPlots/WGLMakie.jl#86]
Just updated to 0.3.2 and when starting up a workbook under Pluto, now getting a pile of:

      From worker 2:    ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for StatsBase [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91]
      From worker 2:    │   exception = Required dependency DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8] failed to load from a cache file.
      From worker 2:    └ @ Base loading.jl:1042
      From worker 2:    ┌ Warning: Module StatsBase with build ID 479272217421486 is missing from the cache.
      From worker 2:    │ This may mean StatsBase [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91] does not support precompilation but is imported by a module that does.
      From worker 2:    └ @ Base loading.jl:1017
      From worker 2:    ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e]
      From worker 2:    │   exception = Required dependency Packing [19eb6ba3-879d-56ad-ad62-d5c202156566] failed to load from a cache file.
      From worker 2:    └ @ Base loading.jl:1042
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for WGLMakie [276b4fcb-3e11-5398-bf8b-a0c2d153d008]
│   exception = Invalid input in module list: expected Ratios.

and unfortunately, even with the jsserv manual patches, I am not getting anything displayed.

**Comment by SimonDanisch** [comment]
I don't know what's going on, but I'm pretty sure this is a julia issue, which seems a bit unstable on 1.6. Switching between versions and packages and using Revise may mess with the precompile cache.

**Comment by woolstar** [comment]
Unfortunately none of those are an issue.  I haven't been switching back and forth on package versions, and I'm still using julia 1.5.3.  Though to be fair I did a complete re-install and did not get this issue.  Now, I'm just back to WGLMakie failing complete with Pluto.
