### ISSUE TITLE
Camera zoom with scroll wheel in Firefox only zooms in.

### ISSUE THREAD

**Issue by woolstar** [JuliaPlots/WGLMakie.jl#88]
Under Chrome the scroll wheel will zoom in and out on a 3D scene using the mouse scroll wheel.  On firefox (Windows 64bit: v85) it only zooms in (scrolling up or down).  Using Pluto with the JSServe patch:

    using JSServe ; Page(exportable=true, offline=true)

    begin
        using Random
        using WGLMakie

        U= rand( -1.:.001:1, 3, 1000 )
        pts= Point3.(U[:,i] for i ∈ 1:size(U,2))
        scene= Scene()
        meshscatter!( scene, pts, markersize= 0.02, color=:red )
        scene
    end

Original pluto workbook:  https://github.com/woolstar/test/blob/master/julia/test_webgl.jl

Using
JSServe v1.2.0
WGLMakie v0.3.2

**Comment by SimonDanisch** [comment]
Can you try this? https://github.com/JuliaPlots/WGLMakie.jl/pull/84

**Comment by woolstar** [comment]
Willing to give it a try if you can point me at a cookbook for testing a branch of an installed module.  Do I just fork the entire thing and rename it locally?  Uninstall the original?

**Comment by SimonDanisch** [comment]
I think you can do:
```
julia>] add https://github.com/koehlerson/WGLMakie.jl#mk/wheelinteraction
```

**Comment by woolstar** [comment]
Was fixed with the updated release.
